default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password:

development:
  database: beacons_data_dev
  <<: *default

test:
  database: beacons_data_test
  <<: *default

production:
  adapter: postgresql